version: '2'

networks:
  nexus-net:
    driver: bridge
    driver_opts:
      "com.docker.network.bridge.name": "nexus-net"
    ipam:
      driver: default
      config:
      - subnet: 10.108.0.0/24
        gateway: 10.108.0.1


services:
  nexus:
    container_name: nexus
    image: sonatype/nexus3
    networks:
      - nexus-net
    volumes:
      - ${VOLUME_PATH}:/nexus-data

  nginx-proxy:
    container_name: nexus-nginx-proxy
    image: nginx
    networks:
      - nexus-net
    links:
      - nexus:nexus
    ports:
      - "80:80"
      - "443:443"
      - "${DOCKER_VIRTUAL_PORT}:${DOCKER_VIRTUAL_PORT}"
      - "${DOCKER_DEV_PORT}:${DOCKER_DEV_PORT}"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
     - nexus

  manage-nexus:
    container_name: nexus-manage
    build: ./nexus/
    image: nexus/manage
    networks:
      - nexus-net
    depends_on:
      - nexus
